remote_theme: mmistakes/minimal-mistakes
plugins:
- jekyll-remote-theme
title: "The Book of Cook"
description: "Home of all the book of cooks"
gitorg: "https://NinjaBreadLord.github.io"
baseurl: /bookofcook