remote_theme: chrisrhymes/bulma-clean-theme
plugins: 
  - jekyll-remote-theme
title: "The Book of Cook"
description: "Home of all the book of cooks"
gitorg: "https://ninjabreadlord.github.io"
baseurl: /indochina
# fixed_navbar: top